server:
  port: 8085
  error:
    include-message: always
    include-binding-errors: always
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: photo
          uri: lb://photo
          predicates:
            - Path=/photo/**
        - id: usermicro
          uri: lb://usermicro
          predicates:
            - Path=/usermicro/**
  sleuth:
    traceId128: true
    sampler:
      probability: 1.0

