server:
  error:
    include-message: always
    include-binding-errors: always
logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG
spring:
  data:
    mongodb:
      host: ${LOCALHOST}
      port: 27017
      database: photo
  sleuth:
    traceId128: true
    sampler:
      probability: 1.0
  boot:
    admin:
      client:
        instance:
          prefer-ip: true
          service-url: http://${LOCALHOST}:8077/
eureka:
  instance:
      preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${LOCALHOST}:8090/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
