server:
  port: 8082

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/userphoto
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true